#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum VideoBackendMetricKind {
    AppsinkSession,
    AppsinkCallback,
    AppsinkFramePublished,
    AppsinkMailboxDropped,
    AppsinkPublishCapped,
    MpvSession,
    MpvCaptureAttempt,
    MpvFramePublished,
    MpvCaptureError,
    NativeSession,
    NativeFramePublished,
    NativeDecodeError,
    NativeSurfaceExported,
    NativeImportCacheHit,
    NativeImportCacheMiss,
    NativeGpuCopy,
    NativeFinalYuvSample,
    NativeGlSurfacePresent,
    NativeLinearBridgePresent,
    NativeDrmSyncobjPresent,
    NativeSyncFilePresent,
    NativeBlockingSyncPresent,
    NativeDirectSurfacePresent,
    NativeWaylandSurfacePresented,
    NativeImportError,
    AppsinkDmaBufImportCacheHit,
    AppsinkDmaBufImportCacheMiss,
    AppsinkDmaBufGpuCopy,
    AppsinkFinalYuvSample,
    CudaTimelineHandoff,
    CudaBlockingSync,
    CudaFinalYuvSample,
    CpuFinalYuvSample,
}

impl VideoBackendMetricKind {
    pub fn as_index(self) -> usize {
        match self {
            Self::AppsinkSession => 0,
            Self::AppsinkCallback => 1,
            Self::AppsinkFramePublished => 2,
            Self::AppsinkMailboxDropped => 3,
            Self::AppsinkPublishCapped => 4,
            Self::MpvSession => 5,
            Self::MpvCaptureAttempt => 6,
            Self::MpvFramePublished => 7,
            Self::MpvCaptureError => 8,
            Self::NativeSession => 9,
            Self::NativeFramePublished => 10,
            Self::NativeDecodeError => 11,
            Self::NativeSurfaceExported => 12,
            Self::NativeImportCacheHit => 13,
            Self::NativeImportCacheMiss => 14,
            Self::NativeGpuCopy => 15,
            Self::NativeFinalYuvSample => 16,
            Self::NativeGlSurfacePresent => 17,
            Self::NativeLinearBridgePresent => 18,
            Self::NativeDrmSyncobjPresent => 19,
            Self::NativeSyncFilePresent => 20,
            Self::NativeBlockingSyncPresent => 21,
            Self::NativeDirectSurfacePresent => 22,
            Self::NativeWaylandSurfacePresented => 23,
            Self::NativeImportError => 24,
            Self::AppsinkDmaBufImportCacheHit => 25,
            Self::AppsinkDmaBufImportCacheMiss => 26,
            Self::AppsinkDmaBufGpuCopy => 27,
            Self::AppsinkFinalYuvSample => 28,
            Self::CudaTimelineHandoff => 29,
            Self::CudaBlockingSync => 30,
            Self::CudaFinalYuvSample => 31,
            Self::CpuFinalYuvSample => 32,
        }
    }

    pub fn label(self) -> &'static str {
        match self {
            Self::AppsinkSession => "appsink_sessions",
            Self::AppsinkCallback => "appsink_callbacks",
            Self::AppsinkFramePublished => "appsink_published",
            Self::AppsinkMailboxDropped => "appsink_mailbox_dropped",
            Self::AppsinkPublishCapped => "appsink_publish_capped",
            Self::MpvSession => "mpv_sessions",
            Self::MpvCaptureAttempt => "mpv_capture_attempts",
            Self::MpvFramePublished => "mpv_published",
            Self::MpvCaptureError => "mpv_capture_errors",
            Self::NativeSession => "native_sessions",
            Self::NativeFramePublished => "native_published",
            Self::NativeDecodeError => "native_decode_errors",
            Self::NativeSurfaceExported => "native_surface_exported",
            Self::NativeImportCacheHit => "native_import_cache_hit",
            Self::NativeImportCacheMiss => "native_import_cache_miss",
            Self::NativeGpuCopy => "native_gpu_copy",
            Self::NativeFinalYuvSample => "native_final_yuv_sample",
            Self::NativeGlSurfacePresent => "native_gl_surface_present",
            Self::NativeLinearBridgePresent => "native_linear_bridge_present",
            Self::NativeDrmSyncobjPresent => "native_drm_syncobj_present",
            Self::NativeSyncFilePresent => "native_sync_file_present",
            Self::NativeBlockingSyncPresent => "native_blocking_sync_present",
            Self::NativeDirectSurfacePresent => "native_direct_surface_present",
            Self::NativeWaylandSurfacePresented => "native_wayland_surface_presented",
            Self::NativeImportError => "native_import_errors",
            Self::AppsinkDmaBufImportCacheHit => "appsink_dmabuf_import_cache_hit",
            Self::AppsinkDmaBufImportCacheMiss => "appsink_dmabuf_import_cache_miss",
            Self::AppsinkDmaBufGpuCopy => "appsink_dmabuf_gpu_copy",
            Self::AppsinkFinalYuvSample => "appsink_final_yuv_sample",
            Self::CudaTimelineHandoff => "cuda_timeline_handoff",
            Self::CudaBlockingSync => "cuda_blocking_sync",
            Self::CudaFinalYuvSample => "cuda_final_yuv_sample",
            Self::CpuFinalYuvSample => "cpu_final_yuv_sample",
        }
    }
}

pub const VIDEO_BACKEND_METRIC_KIND_COUNT: usize = 33;
pub const VIDEO_BACKEND_METRIC_KINDS: [VideoBackendMetricKind; VIDEO_BACKEND_METRIC_KIND_COUNT] = [
    VideoBackendMetricKind::AppsinkSession,
    VideoBackendMetricKind::AppsinkCallback,
    VideoBackendMetricKind::AppsinkFramePublished,
    VideoBackendMetricKind::AppsinkMailboxDropped,
    VideoBackendMetricKind::AppsinkPublishCapped,
    VideoBackendMetricKind::MpvSession,
    VideoBackendMetricKind::MpvCaptureAttempt,
    VideoBackendMetricKind::MpvFramePublished,
    VideoBackendMetricKind::MpvCaptureError,
    VideoBackendMetricKind::NativeSession,
    VideoBackendMetricKind::NativeFramePublished,
    VideoBackendMetricKind::NativeDecodeError,
    VideoBackendMetricKind::NativeSurfaceExported,
    VideoBackendMetricKind::NativeImportCacheHit,
    VideoBackendMetricKind::NativeImportCacheMiss,
    VideoBackendMetricKind::NativeGpuCopy,
    VideoBackendMetricKind::NativeFinalYuvSample,
    VideoBackendMetricKind::NativeGlSurfacePresent,
    VideoBackendMetricKind::NativeLinearBridgePresent,
    VideoBackendMetricKind::NativeDrmSyncobjPresent,
    VideoBackendMetricKind::NativeSyncFilePresent,
    VideoBackendMetricKind::NativeBlockingSyncPresent,
    VideoBackendMetricKind::NativeDirectSurfacePresent,
    VideoBackendMetricKind::NativeWaylandSurfacePresented,
    VideoBackendMetricKind::NativeImportError,
    VideoBackendMetricKind::AppsinkDmaBufImportCacheHit,
    VideoBackendMetricKind::AppsinkDmaBufImportCacheMiss,
    VideoBackendMetricKind::AppsinkDmaBufGpuCopy,
    VideoBackendMetricKind::AppsinkFinalYuvSample,
    VideoBackendMetricKind::CudaTimelineHandoff,
    VideoBackendMetricKind::CudaBlockingSync,
    VideoBackendMetricKind::CudaFinalYuvSample,
    VideoBackendMetricKind::CpuFinalYuvSample,
];
