use super::Transition;
use std::collections::HashMap;

impl Transition {
    pub fn random_candidate_names() -> &'static [&'static str] {
        &[
            "angular",
            "bookflip",
            "bounce",
            "bowtiehorizontal",
            "bowtievertical",
            "bowtiewithparameter",
            "burn",
            "butterflywavescrawler",
            "cannabisleaf",
            "circle",
            "circlecrop",
            "circleopen",
            "colorphase",
            "coord-from-in",
            "crazyparametricfun",
            "colourdistance",
            "crosshatch",
            "crosswarp",
            "crosszoom",
            "cube",
            "directional",
            "directionaleasing",
            "directionalscaled",
            "directionalwarp",
            "directionalwipe",
            "displacement",
            "dissolve",
            "doom",
            "doorway",
            "dreamy",
            "dreamyzoom",
            "edge",
            "fade",
            "fadecolor",
            "fadegrayscale",
            "filmburn",
            "flyeye",
            "glitchdisplace",
            "glitchmemories",
            "gridflip",
            "heart",
            "hexagonalize",
            "horizontalclose",
            "horizontalopen",
            "invertedpagecurl",
            "kaleidoscope",
            "leftright",
            "linearblur",
            "luma",
            "luminancemelt",
            "morph",
            "mosaic",
            "mosaic_transition",
            "multiplyblend",
            "overexposure",
            "perlin",
            "pinwheel",
            "pixelize",
            "polarfunction",
            "polkadotscurtain",
            "powerkaleido",
            "radial",
            "randomnoisex",
            "randomsquares",
            "rectangle",
            "rectanglecrop",
            "ripple",
            "rolls",
            "rotate",
            "rotatescalefade",
            "rotatescalevanish",
            "scale_in",
            "simplezoom",
            "simplezoomout",
            "slides",
            "squareswire",
            "squeeze",
            "staticfade",
            "static_wipe",
            "stereoviewer",
            "swap",
            "swirl",
            "tangentmotionblur",
            "topbottom",
            "tvstatic",
            "undulatingburnout",
            "verticalclose",
            "verticalopen",
            "waterdrop",
            "wind",
            "windowblinds",
            "windowslice",
            "wipedown",
            "wipeleft",
            "wiperight",
            "wipeup",
            "x-axis-translation",
            "zoomincircles",
            "zoomleftwipe",
            "zoomrightwipe",
        ]
    }

    pub fn pick_random() -> Self {
        use rand::Rng;
        let mut rng = rand::thread_rng();
        let variants = Self::random_candidate_names();
        let name = variants[rng.gen_range(0..variants.len())];
        Self::from_name(name)
    }

    pub fn from_name(name: &str) -> Self {
        match name.to_lowercase().as_str() {
            "angular" => Transition::Angular {
                starting_angle: 0.0,
            },
            "bookflip" => Transition::BookFlip,
            "bounce" => Transition::Bounce {
                shadow_colour: [0.0, 0.0, 0.0, 0.6],
                shadow_height: 0.075,
                bounces: 3.0,
            },
            "bowtiehorizontal" => Transition::BowTieHorizontal,
            "bowtievertical" => Transition::BowTieVertical,
            "bowtiewithparameter" => Transition::BowTieWithParameter {
                adjust: 0.5,
                reverse: false,
            },
            "burn" => Transition::Burn,
            "butterflywavescrawler" => Transition::ButterflyWaveScrawler {
                amplitude: 1.0,
                waves: 30.0,
                color_separation: 0.3,
            },
            "cannabisleaf" => Transition::CannabisLeaf,
            "circle" => Transition::Circle,
            "circlecrop" => Transition::CircleCrop {
                bgcolor: [0.0, 0.0, 0.0, 1.0],
            },
            "circleopen" => Transition::CircleOpen {
                smoothness: 0.3,
                opening: true,
            },
            "colorphase" => Transition::ColorPhase,
            "coord-from-in" => Transition::CoordFromIn,
            "crazyparametricfun" => Transition::CrazyParametricFun {
                a: 4.0,
                b: 1.0,
                amplitude: 120.0,
                smoothness: 0.1,
            },
            "colourdistance" => Transition::ColourDistance { power: 5.0 },
            "crosshatch" => Transition::CrossHatch,
            "crosswarp" => Transition::CrossWarp,
            "crosszoom" => Transition::CrossZoom { strength: 0.4 },
            "cube" => Transition::Cube {
                persp: 0.7,
                unzoom: 0.3,
                reflection: 0.4,
                floating: 3.0,
            },
            "directional" => Transition::Directional {
                direction: [0.0, 1.0],
            },
            "directionaleasing" => Transition::DirectionalEasing {
                direction: [0.0, 1.0],
            },
            "directionalscaled" => Transition::DirectionalScaled {
                direction: [0.0, 1.0],
                scale: 0.7,
            },
            "directionalwarp" => Transition::DirectionalWarp {
                direction: [1.0, 0.0],
            },
            "directionalwipe" | "wipe" => Transition::DirectionalWipe {
                direction: [1.0, -1.0],
                smoothness: 0.5,
            },
            "displacement" => Transition::Displacement,
            "dissolve" => Transition::Dissolve {
                line_width: 0.1,
                spread_clr: [1.0, 0.0, 0.0],
                hot_clr: [0.9, 0.9, 0.2],
                pow: 5.0,
                intensity: 1.0,
            },
            "doom" => Transition::Doom {
                bars: 30,
                amplitude: 2.0,
                noise: 0.1,
                frequency: 0.5,
                drip_scale: 0.5,
            },
            "doorway" => Transition::Doorway {
                reflection: 0.4,
                perspective: 0.4,
                depth: 3.0,
            },
            "dreamy" => Transition::Dreamy,
            "dreamyzoom" => Transition::DreamyZoom {
                rotation: 6.0,
                scale: 1.2,
            },
            "edge" => Transition::Edge {
                thickness: 0.001,
                brightness: 8.0,
            },
            "fade" => Transition::Fade,
            "fadecolor" => Transition::FadeColor {
                color: [0.0, 0.0, 0.0],
                color_phase: 0.4,
            },
            "fadegrayscale" => Transition::FadeGrayscale { intensity: 0.3 },
            "filmburn" => Transition::FilmBurn { seed: 2.31 },
            "flyeye" => Transition::FlyEye {
                size: 0.04,
                zoom: 0.5,
                color_separation: 0.3,
            },
            "glitchdisplace" => Transition::GlitchDisplace,
            "glitchmemories" => Transition::GlitchMemories,
            "gridflip" => Transition::GridFlip {
                size: [4, 4],
                pause: 0.1,
                divider_width: 0.05,
                bgcolor: [0.0, 0.0, 0.0, 1.0],
                randomness: 0.1,
            },
            "heart" => Transition::Heart,
            "hexagonalize" => Transition::Hexagonalize {
                steps: 50,
                horizontal_hexagons: 20.0,
            },
            "horizontalclose" => Transition::HorizontalClose,
            "horizontalopen" => Transition::HorizontalOpen,
            "invertedpagecurl" => Transition::InvertedPageCurl,
            "kaleidoscope" => Transition::Kaleidoscope {
                speed: 0.5,
                angle: 1.0,
                power: 0.3,
            },
            "leftright" => Transition::LeftRight,
            "linearblur" => Transition::LinearBlur { intensity: 0.1 },
            "luma" => Transition::Luma,
            "luminancemelt" => Transition::LuminanceMelt {
                direction: true,
                luma_threshold: 0.05,
            },
            "morph" => Transition::Morph { strength: 0.1 },
            "mosaic" => Transition::Mosaic { endx: 2, endy: -1 },
            "mosaic_transition" => Transition::MosaicTransition { mosaic_num: 10.0 },
            "multiplyblend" => Transition::MultiplyBlend,
            "overexposure" => Transition::Overexposure,
            "perlin" => Transition::Perlin {
                scale: 4.0,
                smoothness: 0.01,
                seed: 12.0,
            },
            "pinwheel" => Transition::Pinwheel { speed: 2.0 },
            "pixelize" => Transition::Pixelize {
                squares_min: [20, 20],
                steps: 50,
            },
            "polarfunction" => Transition::PolarFunction { segments: 5 },
            "polkadotscurtain" => Transition::PolkaDotsCurtain {
                dots: 20.0,
                center: [0.0, 0.0],
            },
            "powerkaleido" => Transition::PowerKaleido {
                scale: 2.0,
                radius: 1.5,
                angle: 0.0,
            },
            "radial" => Transition::Radial { smoothness: 1.0 },
            "randomnoisex" => Transition::RandomNoiseX,
            "randomsquares" => Transition::RandomSquares {
                size: [10, 10],
                smoothness: 0.5,
            },
            "rectangle" => Transition::Rectangle {
                bgcolor: [0.0, 0.0, 0.0, 1.0],
            },
            "rectanglecrop" => Transition::RectangleCrop {
                bgcolor: [0.0, 0.0, 0.0, 1.0],
            },
            "ripple" => Transition::Ripple {
                amplitude: 100.0,
                speed: 50.0,
            },
            "rolls" => Transition::Rolls {
                rolls_type: 0,
                rot_down: false,
            },
            "rotate" => Transition::Rotate,
            "rotatescalefade" => Transition::RotateScaleFade {
                center: [0.5, 0.5],
                rotations: 1.0,
                scale: 8.0,
                back_color: [0.15, 0.15, 0.15, 1.0],
            },
            "rotatescalevanish" => Transition::RotateScaleVanish {
                fade_in_second: true,
                reverse_effect: false,
                reverse_rotation: false,
            },
            "scale_in" => Transition::ScaleIn,
            "simplezoom" => Transition::SimpleZoom {
                zoom_quickness: 0.8,
            },
            "simplezoomout" => Transition::SimpleZoomOut {
                zoom_quickness: 0.8,
                fade_edge: true,
            },
            "slides" => Transition::Slides {
                slides_type: 0,
                slides_in: false,
            },
            "squareswire" => Transition::SquaresWire {
                squares: [10, 10],
                direction: [1.0, -0.5],
                smoothness: 1.6,
            },
            "squeeze" => Transition::Squeeze {
                color_separation: 0.1,
            },
            "staticfade" => Transition::StaticFade {
                n_noise_pixels: 200.0,
                static_luminosity: 0.8,
            },
            "static_wipe" => Transition::StaticWipe {
                up_to_down: true,
                max_static_span: 0.5,
            },
            "stereoviewer" => Transition::StereoViewer {
                zoom: 0.88,
                corner_radius: 0.22,
            },
            "swap" => Transition::Swap {
                reflection: 0.4,
                perspective: 0.2,
                depth: 3.0,
            },
            "swirl" => Transition::Swirl,
            "tangentmotionblur" => Transition::TangentMotionBlur,
            "topbottom" => Transition::TopBottom,
            "tvstatic" => Transition::TvStatic { offset: 0.05 },
            "undulatingburnout" => Transition::UndulatingBurnOut {
                smoothness: 0.03,
                center: [0.5, 0.5],
                color: [0.0, 0.0, 0.0],
            },
            "verticalclose" => Transition::VerticalClose,
            "verticalopen" => Transition::VerticalOpen,
            "waterdrop" => Transition::WaterDrop {
                amplitude: 30.0,
                speed: 30.0,
            },
            "wind" => Transition::Wind { size: 0.05 },
            "windowblinds" => Transition::WindowBlinds,
            "windowslice" => Transition::WindowSlice {
                count: 10.0,
                smoothness: 0.5,
            },
            "wipedown" => Transition::WipeDown,
            "wipeleft" => Transition::WipeLeft,
            "wiperight" => Transition::WipeRight,
            "wipeup" => Transition::WipeUp,
            "x-axis-translation" => Transition::XAxisTranslation,
            "zoomincircles" => Transition::ZoomInCircles,
            "zoomleftwipe" => Transition::ZoomLeftWipe {
                zoom_quickness: 0.8,
            },
            "zoomrightwipe" => Transition::ZoomRightWipe {
                zoom_quickness: 0.8,
            },
            "random" => Transition::Random,
            _ => Transition::Fade,
        }
    }

    pub fn name(&self) -> String {
        match self {
            Transition::Angular { .. } => "angular".to_string(),
            Transition::BookFlip => "BookFlip".to_string(),
            Transition::Bounce { .. } => "Bounce".to_string(),
            Transition::BowTieHorizontal => "BowTieHorizontal".to_string(),
            Transition::BowTieVertical => "BowTieVertical".to_string(),
            Transition::BowTieWithParameter { .. } => "BowTieWithParameter".to_string(),
            Transition::Burn => "burn".to_string(),
            Transition::ButterflyWaveScrawler { .. } => "ButterflyWaveScrawler".to_string(),
            Transition::CannabisLeaf => "cannabisleaf".to_string(),
            Transition::Circle => "circle".to_string(),
            Transition::CircleCrop { .. } => "CircleCrop".to_string(),
            Transition::CircleOpen { .. } => "circleopen".to_string(),
            Transition::ColorPhase => "colorphase".to_string(),
            Transition::CoordFromIn => "coord-from-in".to_string(),
            Transition::CrazyParametricFun { .. } => "CrazyParametricFun".to_string(),
            Transition::ColourDistance { .. } => "ColourDistance".to_string(),
            Transition::CrossHatch => "crosshatch".to_string(),
            Transition::CrossWarp => "crosswarp".to_string(),
            Transition::CrossZoom { .. } => "CrossZoom".to_string(),
            Transition::Cube { .. } => "cube".to_string(),
            Transition::Directional { .. } => "Directional".to_string(),
            Transition::DirectionalEasing { .. } => "directional-easing".to_string(),
            Transition::DirectionalScaled { .. } => "DirectionalScaled".to_string(),
            Transition::DirectionalWarp { .. } => "directionalwarp".to_string(),
            Transition::DirectionalWipe { .. } => "directionalwipe".to_string(),
            Transition::Displacement => "displacement".to_string(),
            Transition::Dissolve { .. } => "dissolve".to_string(),
            Transition::Doom { .. } => "DoomScreenTransition".to_string(),
            Transition::Doorway { .. } => "doorway".to_string(),
            Transition::Dreamy => "Dreamy".to_string(),
            Transition::DreamyZoom { .. } => "DreamyZoom".to_string(),
            Transition::Edge { .. } => "EdgeTransition".to_string(),
            Transition::Fade => "fade".to_string(),
            Transition::FadeColor { .. } => "fadecolor".to_string(),
            Transition::FadeGrayscale { .. } => "fadegrayscale".to_string(),
            Transition::FilmBurn { .. } => "FilmBurn".to_string(),
            Transition::FlyEye { .. } => "flyeye".to_string(),
            Transition::GlitchDisplace => "GlitchDisplace".to_string(),
            Transition::GlitchMemories => "GlitchMemories".to_string(),
            Transition::GridFlip { .. } => "GridFlip".to_string(),
            Transition::Heart => "heart".to_string(),
            Transition::Hexagonalize { .. } => "hexagonalize".to_string(),
            Transition::HorizontalClose => "HorizontalClose".to_string(),
            Transition::HorizontalOpen => "HorizontalOpen".to_string(),
            Transition::InvertedPageCurl => "InvertedPageCurl".to_string(),
            Transition::Kaleidoscope { .. } => "kaleidoscope".to_string(),
            Transition::LeftRight => "LeftRight".to_string(),
            Transition::LinearBlur { .. } => "LinearBlur".to_string(),
            Transition::Luma => "luma".to_string(),
            Transition::LuminanceMelt { .. } => "luminance_melt".to_string(),
            Transition::Morph { .. } => "morph".to_string(),
            Transition::Mosaic { .. } => "Mosaic".to_string(),
            Transition::MosaicTransition { .. } => "mosaic_transition".to_string(),
            Transition::MultiplyBlend => "multiply_blend".to_string(),
            Transition::Overexposure => "Overexposure".to_string(),
            Transition::Perlin { .. } => "perlin".to_string(),
            Transition::Pinwheel { .. } => "pinwheel".to_string(),
            Transition::Pixelize { .. } => "pixelize".to_string(),
            Transition::PolarFunction { .. } => "polar_function".to_string(),
            Transition::PolkaDotsCurtain { .. } => "PolkaDotsCurtain".to_string(),
            Transition::PowerKaleido { .. } => "powerKaleido".to_string(),
            Transition::Radial { .. } => "Radial".to_string(),
            Transition::RandomNoiseX => "randomNoisex".to_string(),
            Transition::RandomSquares { .. } => "randomsquares".to_string(),
            Transition::Rectangle { .. } => "Rectangle".to_string(),
            Transition::RectangleCrop { .. } => "RectangleCrop".to_string(),
            Transition::Ripple { .. } => "ripple".to_string(),
            Transition::Rolls { .. } => "Rolls".to_string(),
            Transition::Rotate => "rotateTransition".to_string(),
            Transition::RotateScaleFade { .. } => "rotate_scale_fade".to_string(),
            Transition::RotateScaleVanish { .. } => "RotateScaleVanish".to_string(),
            Transition::ScaleIn => "scale-in".to_string(),
            Transition::SimpleZoom { .. } => "SimpleZoom".to_string(),
            Transition::SimpleZoomOut { .. } => "SimpleZoomOut".to_string(),
            Transition::Slides { .. } => "Slides".to_string(),
            Transition::SquaresWire { .. } => "squareswire".to_string(),
            Transition::Squeeze { .. } => "squeeze".to_string(),
            Transition::StaticFade { .. } => "StaticFade".to_string(),
            Transition::StaticWipe { .. } => "static_wipe".to_string(),
            Transition::StereoViewer { .. } => "StereoViewer".to_string(),
            Transition::Swap { .. } => "swap".to_string(),
            Transition::Swirl => "Swirl".to_string(),
            Transition::TangentMotionBlur => "tangentMotionBlur".to_string(),
            Transition::TopBottom => "TopBottom".to_string(),
            Transition::TvStatic { .. } => "TVStatic".to_string(),
            Transition::UndulatingBurnOut { .. } => "undulatingBurnOut".to_string(),
            Transition::VerticalClose => "VerticalClose".to_string(),
            Transition::VerticalOpen => "VerticalOpen".to_string(),
            Transition::WaterDrop { .. } => "WaterDrop".to_string(),
            Transition::Wind { .. } => "wind".to_string(),
            Transition::WindowBlinds => "windowblinds".to_string(),
            Transition::WindowSlice { .. } => "windowslice".to_string(),
            Transition::WipeDown => "wipeDown".to_string(),
            Transition::WipeLeft => "wipeLeft".to_string(),
            Transition::WipeRight => "wipeRight".to_string(),
            Transition::WipeUp => "wipeUp".to_string(),
            Transition::XAxisTranslation => "x_axis_translation".to_string(),
            Transition::ZoomInCircles => "ZoomInCircles".to_string(),
            Transition::ZoomLeftWipe { .. } => "ZoomLeftWipe".to_string(),
            Transition::ZoomRightWipe { .. } => "ZoomRigthWipe".to_string(),
            Transition::Random => "random".to_string(),
            Transition::Custom { shader, .. } => shader.clone(),
        }
    }
}
